# input = "inputfs"
# output = "fs"
# src_dir = "git"

[[entries]]
url = "https://github.com/luciusmagn/sbase"
name = "sbase"
cmds = [
	"./build.sh",
	"cp grep egrep",
	"cp grep fgrep",
]
paths = [
	["cmp", "bin"],
	["grep", "bin"],
	["egrep", "bin"],
	["fgrep", "bin"],
	["rev", "bin"],
	["sed", "bin"],
	["tar", "bin"],
]

# egrep, fgrep

[[entries]]
url = "https://github.com/luciusmagn/ubase"
name = "ubase"
cmds = ["make"]
paths = [
	["mknod", "bin"],
	["stat", "bin"],
]

[[entries]]
url = "https://github.com/luciusmagn/9base"
name = "9base"
cmds = ["make"]
paths = [
	["awk/awk", "bin"],
	["diff/diff", "bin"],
]

[[entries]]
url = "https://github.com/luciusmagn/find-static"
name = "find-static"
cmds = ["./build.sh"]
paths = [
	["releases/find", "bin"],
	["releases/xargs", "bin"],
]

[[entries]]
url = "https://github.com/luciusmagn/bash-static"
name = "bash-static"
cmds = ["./build.sh"]
paths = [
	["releases/bash", "bin"]
]

# remove all .gitignore files from the fs
install = [
	"find <<target>> -name .gitignore -type f -delete"
]

[[entries]]
url = "https://github.com/luciusmagn/coreutils-static"
name = "coreutils-static"
cmds = ["./build.sh"]
paths = [
	["releases/[", "bin"],
	["releases/base32", "bin"],
	["releases/base64", "bin"],
	["releases/basename", "bin"],
	["releases/cat", "bin"],
	["releases/chmod", "bin"],
	["releases/cksum", "bin"],
	["releases/comm", "bin"],
	["releases/cp", "bin"],
	["releases/csplit", "bin"],
	["releases/cut", "bin"],
	["releases/date", "bin"],
	["releases/dd", "bin"],
	["releases/dir", "bin"],
	["releases/dirname", "bin"],
	["releases/cksum", "bin"],
	["releases/du", "bin"],
	["releases/echo", "bin"],
	["releases/env", "bin"],
	["releases/expand", "bin"],
	["releases/expr", "bin"],
	["releases/factor", "bin"],
	["releases/false", "bin"],
	["releases/fmt", "bin"],
	["releases/fold", "bin"],
	["releases/groups", "bin"],
	["releases/head", "bin"],
	["releases/hostid", "bin"],
	["releases/id", "bin"],
	["releases/join", "bin"],
	["releases/link", "bin"],
	["releases/ln", "bin"],
	["releases/logname", "bin"],
	["releases/ls", "bin"],
	["releases/md5sum", "bin"],
	["releases/mkdir", "bin"],
	["releases/mkfifo", "bin"],
	["releases/mktemp", "bin"],
	["releases/mv", "bin"],
	["releases/nl", "bin"],
	["releases/numfmt", "bin"],
	["releases/od", "bin"],
	["releases/paste", "bin"],
	["releases/pathchk", "bin"],
	["releases/pr", "bin"],
	["releases/printenv", "bin"],
	["releases/printf", "bin"],
	["releases/ptx", "bin"],
	["releases/pwd", "bin"],
	["releases/readlink", "bin"],
	["releases/realpath", "bin"],
	["releases/rm", "bin"],
	["releases/rmdir", "bin"],
	["releases/seq", "bin"],
	["releases/sha1sum", "bin"],
	["releases/sha224sum", "bin"],
	["releases/sha256sum", "bin"],
	["releases/sha384sum", "bin"],
	["releases/sha512sum", "bin"],
	["releases/shred", "bin"],
	["releases/shuf", "bin"],
	["releases/sleep", "bin"],
	["releases/sort", "bin"],
	["releases/split", "bin"],
	["releases/stat", "bin"],
	["releases/sum", "bin"],
	["releases/tac", "bin"],
	["releases/tail", "bin"],
	["releases/tee", "bin"],
	["releases/test", "bin"],
	["releases/timeout", "bin"],
	["releases/touch", "bin"],
	["releases/tr", "bin"],
	["releases/true", "bin"],
	["releases/truncate", "bin"],
	["releases/tsort", "bin"],
	["releases/unexpand", "bin"],
	["releases/uniq", "bin"],
	["releases/unlink", "bin"],
	["releases/vdir", "bin"],
	["releases/wc", "bin"],
	["releases/who", "bin"],
	["releases/whoami", "bin"],
	["releases/yes", "bin"],
]


[[entries]]
url = "https://github.com/luciusmagn/gawk-static"
name = "gawk-static"
cmds = ["./build.sh"]
paths = [
	["releases/gawk", "bin"]
]

[[entries]]
url = "https://github.com/luciusmagn/sed-static"
name = "sed-static"
cmds = ["./build.sh"]
paths = [
	["releases/sed", "bin"]
]
