[package]
name = "install"
version = "0.1.0"
authors = ["Lukáš Hozda <luk.hozda@gmail.com>"]

[dependencies]
serde = "1.0.14"
toml = "0.4.5"
serde_derive = "1.0.14"
pbr = "1.0.0"
#copy_dir = "0.1.2"
ansi_term = "0.9.0"
